### ISSUE TITLE
Search problems

### ISSUE THREAD

**Issue by beshoo** [yznetaX/mujeebk#21]
1- When you click on search for missing value you will have alert error (2 times ???) **THIS HAPPENED SOMETIMES**
( Please change the alert to snakbar )
2 - when you hover on the option it is cuted please have a look 
https://i.vgy.me/POt70j.png it has to be complete 100% to the menu width.

3- The title is very BIG
Search Results
Results for ' sss'
Remove the "Search Results" words. and make the 
Results for ' sss' and thE Recycle Bin IN ONE LINE...

4- Please remove this radius 
https://i.vgy.me/whIlGy.png

5- Please make a 1px border around the search input box with his color **#e8e8e8**

6- search does not fiend  included words
https://i.vgy.me/RCLWJL.png

7- Textarea is limited only for 4 lines and if i click outside it will get back to 1 row, and if I click on it it will expand 
https://i.vgy.me/5R8dnv.png

8- What is this shadow  ????
https://i.vgy.me/AhJf82.png

9- enlarge the dialog window
https://i.vgy.me/DlUJg8.png

10- text is cited in the textarea 
https://i.vgy.me/6HDbl1.png

**Comment by yznetaX** [comment]
ok i am working on them thank you
